### ISSUE TITLE
How do I register storedQueries?

### ISSUE THREAD

**Issue by shyoon87** [3dcitydb/web-feature-service#6]
hi.

I am trying to visualize the building using WFS.

How do I Register storedQueries?

------------------
Worked process.
1. installed 3dcitydb (postGIS)
2. import NY 3d data (download 3dcitydb site)
3. install tomcat and 3dcitydb web-feature-service war
4. edit config.xml  ( db connecting ), add lib (related postgis jar)
5. run tomcat (wfs server)
6. do request:   http://localhost:81/citydb-wfs/wfs?SERVICE=WFS&REQUEST=ListStoredQueries&version=2.0.2

response: 
<wfs:ListStoredQueriesResponse xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd">
<wfs:StoredQuery id="http://www.opengis.net/def/query/OGC-WFS/0/GetFeatureById">
<wfs:Title xml:lang="en">Get feature by identifier</wfs:Title>
</wfs:StoredQuery>
</wfs:ListStoredQueriesResponse>

Where is my storedQueries???   :(

**Comment by clausnagel** [comment]
Not quite sure that I get your questions. The above response shows that there is a stored query `http://www.opengis.net/def/query/OGC-WFS/0/GetFeatureById` that lets you query a building by its identifier (which is the `gml:id`).

So, next step is to make a request using this stored query, pass a `gml:id` as parameter and get back the corresponding building as response.

Examples can be found here: https://3dcitydb-docs.readthedocs.io/en/release-v4.2.3/wfs/functionality.html#getfeature-operation

**Comment by shyoon87** [comment]
Where can I find "gml: id"?

![캡처](https://user-images.githubusercontent.com/45777536/81275615-e4670780-908c-11ea-9d6e-0a33217b7e62.PNG)

**Comment by clausnagel** [comment]
The `gml:id` is a property of the building object. It is stored in the column `GMLID` of the table `CITYOBJECT` for each building. You must know the `gml:id` in order to use the WFS query. The query takes the `gml:id` as parameter and the WFS will return only that building from the database that belongs to the provided `gml:id`.

Put differently, the `GetFeatureById` query uses the `gml:id` as filter.

As documented in the link I posted above, you can, for instance, send the following query to the WFS:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<wfs:GetFeature service="WFS" version="2.0.0"
 xmlns:wfs="http://www.opengis.net/wfs/2.0">
  <wfs:StoredQuery id="http://www.opengis.net/def/query/OGC-WFS/0/GetFeatureById">
    <wfs:Parameter name="id">ID_0815</wfs:Parameter>
  </wfs:StoredQuery>
</wfs:GetFeature>

```

The WFS will then search the database for a building having a `gml:id` of value `ID_0815`. If there is such a building in the database, the WFS will return it. Otherwise, an exception message will be returned.

**Comment by clausnagel** [comment]
Closing this issue. Feel free to re-open if your question has not been answered.
